"use client";
import { useState } from "react";

export default function VideoButton({ prompt }: { prompt: string }) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [videoUrl, setVideoUrl] = useState<string | null>(null);

  async function generate() {
    setState("loading");
    try {
      const res = await fetch("/api/video", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: `Educational visualization of AI concept: ${prompt}. Abstract, clean, futuristic style with neural networks and data flowing.`,
        }),
      });
      const data = await res.json();
      if (data.videoUrl) {
        setVideoUrl(data.videoUrl);
        setState("done");
      } else {
        setState("error");
      }
    } catch {
      setState("error");
    }
  }

  if (state === "done" && videoUrl) {
    return (
      <div className="rounded-xl overflow-hidden border border-accent2/30">
        <video src={videoUrl} controls autoPlay muted loop className="w-full" />
        <div className="px-3 py-1.5 text-[9px] text-gray-600 bg-ink/80">
          Generated by Pika
        </div>
      </div>
    );
  }

  return (
    <button
      onClick={generate}
      disabled={state === "loading"}
      className={
        "inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs transition " +
        (state === "loading"
          ? "border-edge text-gray-500 animate-pulse"
          : state === "error"
          ? "border-bad/50 text-bad"
          : "border-edge text-gray-400 hover:border-accent/50 hover:text-accent")
      }
    >
      {state === "loading" ? "Generating..." : state === "error" ? "Failed — retry" : "▶ Generate Video"}
      <span className="text-[9px] text-gray-600">Pika</span>
    </button>
  );
}
